### ISSUE TITLE
请问这个程序怎么用，能写个教程么？

### ISSUE THREAD

**Issue by williamnie** [Zix777/XMemo#1]
老铁，我实在deepin论坛上看到了，昨天刚换了deepin，刚刚下载在github上直接下载了源代码，直接在bin文件夹下面运行就可以启动程序，想问问我这样使用对么，还是需要安装，这样不是很方便，而且不是很美观，老铁能给个使用方法么，谢谢了！

**Comment by xyz1001** [comment]
我打个包给你

**Comment by williamnie** [comment]
谢谢老铁了，你的deepin用着怎样，我的还是有第一点问题，可能还是要等下个版本的更新，

**Comment by xyz1001** [comment]
目前没有影响使用的大问题，只有些小的问题影响体验
