### ISSUE TITLE
make failed  

### ISSUE THREAD

**Issue by zhaoxuli** [Zix777/XMemo#2]
qmake is okay 
but when I try to make  MemoWidget.o  it failed like this:
![image](https://user-images.githubusercontent.com/37375362/41326600-3df51cf6-6ef2-11e8-8a8b-1bf85137713a.png)

Thanks ~

**Comment by xyz1001** [comment]
you need to install boost first.
Ubuntu
 `sudo apt-get install libboost-all-dev`
arch
`sudo pacman -S boost-libs`

**Comment by zhaoxuli** [comment]
Okay, thanks a lot  😄😄
